package com.hulles.alixia.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _MediaFile was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MediaFile extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String MEDIA_FILE_ID_PK_COLUMN = "media_file_ID";

    public static final Property<String> ARTIST = Property.create("artist", String.class);
    public static final Property<String> FILE_NAME = Property.create("fileName", String.class);
    public static final Property<String> FORMAT_CODE = Property.create("formatCode", String.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<LocalDateTime> FILE_LAST_MODIFIED = Property.create("fileLastModified", LocalDateTime.class);

    protected String artist;
    protected String fileName;
    protected String formatCode;
    protected String title;
    protected LocalDateTime fileLastModified;


    public void setArtist(String artist) {
        beforePropertyWrite("artist", this.artist, artist);
        this.artist = artist;
    }

    public String getArtist() {
        beforePropertyRead("artist");
        return this.artist;
    }

    public void setFileName(String fileName) {
        beforePropertyWrite("fileName", this.fileName, fileName);
        this.fileName = fileName;
    }

    public String getFileName() {
        beforePropertyRead("fileName");
        return this.fileName;
    }

    public void setFormatCode(String formatCode) {
        beforePropertyWrite("formatCode", this.formatCode, formatCode);
        this.formatCode = formatCode;
    }

    public String getFormatCode() {
        beforePropertyRead("formatCode");
        return this.formatCode;
    }

    public void setTitle(String title) {
        beforePropertyWrite("title", this.title, title);
        this.title = title;
    }

    public String getTitle() {
        beforePropertyRead("title");
        return this.title;
    }

    public void setFileLastModified(LocalDateTime fileLastModified) {
        beforePropertyWrite("fileLastModified", this.fileLastModified, fileLastModified);
        this.fileLastModified = fileLastModified;
    }

    public LocalDateTime getFileLastModified() {
        beforePropertyRead("fileLastModified");
        return this.fileLastModified;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "artist":
                return this.artist;
            case "fileName":
                return this.fileName;
            case "formatCode":
                return this.formatCode;
            case "title":
                return this.title;
            case "fileLastModified":
                return this.fileLastModified;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "artist":
                this.artist = (String)val;
                break;
            case "fileName":
                this.fileName = (String)val;
                break;
            case "formatCode":
                this.formatCode = (String)val;
                break;
            case "title":
                this.title = (String)val;
                break;
            case "fileLastModified":
                this.fileLastModified = (LocalDateTime)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.artist);
        out.writeObject(this.fileName);
        out.writeObject(this.formatCode);
        out.writeObject(this.title);
        out.writeObject(this.fileLastModified);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.artist = (String)in.readObject();
        this.fileName = (String)in.readObject();
        this.formatCode = (String)in.readObject();
        this.title = (String)in.readObject();
        this.fileLastModified = (LocalDateTime)in.readObject();
    }

}
