package com.hulles.alixia.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import com.hulles.alixia.cayenne.Task;

/**
 * Class _TaskType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TaskType extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String TASK_TYPE_ID_PK_COLUMN = "task_type_ID";

    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> TASK_TYPE_UUID = Property.create("taskTypeUuid", String.class);
    public static final Property<List<Task>> TASKS = Property.create("tasks", List.class);

    protected String description;
    protected String taskTypeUuid;

    protected Object tasks;

    public void setDescription(String description) {
        beforePropertyWrite("description", this.description, description);
        this.description = description;
    }

    public String getDescription() {
        beforePropertyRead("description");
        return this.description;
    }

    public void setTaskTypeUuid(String taskTypeUuid) {
        beforePropertyWrite("taskTypeUuid", this.taskTypeUuid, taskTypeUuid);
        this.taskTypeUuid = taskTypeUuid;
    }

    public String getTaskTypeUuid() {
        beforePropertyRead("taskTypeUuid");
        return this.taskTypeUuid;
    }

    public void addToTasks(Task obj) {
        addToManyTarget("tasks", obj, true);
    }

    public void removeFromTasks(Task obj) {
        removeToManyTarget("tasks", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Task> getTasks() {
        return (List<Task>)readProperty("tasks");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "description":
                return this.description;
            case "taskTypeUuid":
                return this.taskTypeUuid;
            case "tasks":
                return this.tasks;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "description":
                this.description = (String)val;
                break;
            case "taskTypeUuid":
                this.taskTypeUuid = (String)val;
                break;
            case "tasks":
                this.tasks = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.description);
        out.writeObject(this.taskTypeUuid);
        out.writeObject(this.tasks);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.description = (String)in.readObject();
        this.taskTypeUuid = (String)in.readObject();
        this.tasks = in.readObject();
    }

}
