package com.hulles.alixia.delta.deepspeech.swig;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class implJNI {
    public final static native long new_modelstatep();
    public final static native long copy_modelstatep(long jarg1);
    public final static native void delete_modelstatep(long jarg1);
    public final static native void modelstatep_assign(long jarg1, long jarg2);
    public final static native long modelstatep_value(long jarg1);
    public final static native long new_streamingstatep();
    public final static native long copy_streamingstatep(long jarg1);
    public final static native void delete_streamingstatep(long jarg1);
    public final static native void streamingstatep_assign(long jarg1, long jarg2);
    public final static native long streamingstatep_value(long jarg1);
    public final static native long new_metadataItem_array(int jarg1);
    public final static native void delete_metadataItem_array(long jarg1, MetadataItem jarg1_);
    public final static native long metadataItem_array_getitem(long jarg1, MetadataItem jarg1_, int jarg2);
    public final static native void metadataItem_array_setitem(long jarg1, MetadataItem jarg1_, int jarg2, long jarg3, MetadataItem jarg3_);
    public final static native void MetadataItem_character_set(long jarg1, MetadataItem jarg1_, String jarg2);
    public final static native String MetadataItem_character_get(long jarg1, MetadataItem jarg1_);
    public final static native void MetadataItem_timestep_set(long jarg1, MetadataItem jarg1_, int jarg2);
    public final static native int MetadataItem_timestep_get(long jarg1, MetadataItem jarg1_);
    public final static native void MetadataItem_start_time_set(long jarg1, MetadataItem jarg1_, float jarg2);
    public final static native float MetadataItem_start_time_get(long jarg1, MetadataItem jarg1_);
    public final static native void Metadata_items_set(long jarg1, Metadata jarg1_, long jarg2, MetadataItem jarg2_);
    public final static native long Metadata_items_get(long jarg1, Metadata jarg1_);
    public final static native void Metadata_num_items_set(long jarg1, Metadata jarg1_, int jarg2);
    public final static native int Metadata_num_items_get(long jarg1, Metadata jarg1_);
    public final static native void Metadata_confidence_set(long jarg1, Metadata jarg1_, double jarg2);
    public final static native double Metadata_confidence_get(long jarg1, Metadata jarg1_);
    public final static native long Metadata_getItem(long jarg1, Metadata jarg1_, int jarg2);
    public final static native void delete_Metadata(long jarg1);
    public final static native int ERR_OK_get();
    public final static native int ERR_NO_MODEL_get();
    public final static native int ERR_INVALID_ALPHABET_get();
    public final static native int ERR_INVALID_SHAPE_get();
    public final static native int ERR_INVALID_LM_get();
    public final static native int ERR_MODEL_INCOMPATIBLE_get();
    public final static native int ERR_FAIL_INIT_MMAP_get();
    public final static native int ERR_FAIL_INIT_SESS_get();
    public final static native int ERR_FAIL_INTERPRETER_get();
    public final static native int ERR_FAIL_RUN_SESS_get();
    public final static native int ERR_FAIL_CREATE_STREAM_get();
    public final static native int ERR_FAIL_READ_PROTOBUF_get();
    public final static native int ERR_FAIL_CREATE_SESS_get();
    public final static native int ERR_FAIL_CREATE_MODEL_get();
    public final static native int CreateModel(String jarg1, long jarg2, long jarg3);
    public final static native int GetModelSampleRate(long jarg1);
    public final static native void FreeModel(long jarg1);
    public final static native int EnableDecoderWithLM(long jarg1, String jarg2, String jarg3, float jarg4, float jarg5);
    public final static native String SpeechToText(long jarg1, short[] jarg2, long jarg3);
    public final static native long SpeechToTextWithMetadata(long jarg1, short[] jarg2, long jarg3);
    public final static native int CreateStream(long jarg1, long jarg2);
    public final static native void FeedAudioContent(long jarg1, short[] jarg2, long jarg3);
    public final static native String IntermediateDecode(long jarg1);
    public final static native String FinishStream(long jarg1);
    public final static native long FinishStreamWithMetadata(long jarg1);
    public final static native void FreeStream(long jarg1);
    public final static native void FreeMetadata(long jarg1, Metadata jarg1_);
    public final static native void FreeString(String jarg1);
    public final static native void PrintVersions();
}
