/*******************************************************************************
 * Copyright © 2017, 2018 Hulles Industries LLC
 * All rights reserved
 *  
 * This file is part of A1icia.
 *  
 * A1icia is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *    
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *  
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifer: GPL-3.0-or-later
 *******************************************************************************/
package com.hulles.a1icia.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import com.hulles.a1icia.cayenne.Country;

/**
 * Class _OwmCity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OwmCity extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String OWM_CITY_ID_PK_COLUMN = "owm_city_ID";

    public static final Property<Float> LATITUDE = Property.create("latitude", Float.class);
    public static final Property<Float> LONGITUDE = Property.create("longitude", Float.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<Integer> OWM_ID = Property.create("owmId", Integer.class);
    public static final Property<Country> COUNTRY = Property.create("country", Country.class);

    protected float latitude;
    protected float longitude;
    protected String name;
    protected int owmId;

    protected Object country;

    public void setLatitude(Float latitude) {
        beforePropertyWrite("latitude", this.latitude, latitude);
        this.latitude = latitude;
    }

    public Float getLatitude() {
        beforePropertyRead("latitude");
        return this.latitude;
    }

    public void setLongitude(Float longitude) {
        beforePropertyWrite("longitude", this.longitude, longitude);
        this.longitude = longitude;
    }

    public Float getLongitude() {
        beforePropertyRead("longitude");
        return this.longitude;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setOwmId(Integer owmId) {
        beforePropertyWrite("owmId", this.owmId, owmId);
        this.owmId = owmId;
    }

    public Integer getOwmId() {
        beforePropertyRead("owmId");
        return this.owmId;
    }

    public void setCountry(Country country) {
        setToOneTarget("country", country, true);
    }

    public Country getCountry() {
        return (Country)readProperty("country");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "latitude":
                return this.latitude;
            case "longitude":
                return this.longitude;
            case "name":
                return this.name;
            case "owmId":
                return this.owmId;
            case "country":
                return this.country;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "latitude":
                this.latitude = val == null ? 0 : (float)val;
                break;
            case "longitude":
                this.longitude = val == null ? 0 : (float)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "owmId":
                this.owmId = val == null ? 0 : (int)val;
                break;
            case "country":
                this.country = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeFloat(this.latitude);
        out.writeFloat(this.longitude);
        out.writeObject(this.name);
        out.writeInt(this.owmId);
        out.writeObject(this.country);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.latitude = in.readFloat();
        this.longitude = in.readFloat();
        this.name = (String)in.readObject();
        this.owmId = in.readInt();
        this.country = in.readObject();
    }

}
